services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ${LOCAL_DOWNLOADS_PATH:-shared_downloads}:/downloads
    networks:
      - nas_network

  videotranscoder:
    build: ./videotranscoder
    container_name: videotranscoder
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - ${LOCAL_DOWNLOADS_PATH:-shared_downloads}:/share
    networks:
      - nas_network

  nas:
    image: dperson/samba
    container_name: nas
    restart: unless-stopped
    environment:
      - TZ=UTC
      - WORKGROUP=WORKGROUP
      # Format: user;password[;ID;group]
      - USERID=1000
      - USER=FreakiestNas;FreakiestNas
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - shared_downloads:/share
    command: '-s "Downloads;/share;yes;no;yes;all;none;none" -u "FreakiestNas;FreakiestNas" -p'
    networks:
      - nas_network
    profiles:
      - with_nas

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - nas_network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nas_network

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      - TZ=UTC
      - WEBPASSWORD=FreakiestNas
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
    volumes:
      - pihole_data:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    networks:
      - nas_network
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "3002:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
    networks:
      - nas_network

volumes:
  shared_downloads:
    driver: local
    driver_opts:
      type: none
      device: /share/docker_volumes/shared_downloads
      o: bind
  ollama_data:
    driver: local
    driver_opts:
      type: none
      device: /share/docker_volumes/ollama_data
      o: bind
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /share/docker_volumes/portainer_data
      o: bind
  pihole_data:
    driver: local
    driver_opts:
      type: none
      device: /share/docker_volumes/pihole_data
      o: bind
  pihole_dnsmasq:
    driver: local
    driver_opts:
      type: none
      device: /share/docker_volumes/pihole_dnsmasq
      o: bind

networks:
  nas_network:
    driver: bridge
