services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ${LOCAL_DOWNLOADS_PATH:-shared_downloads}:/downloads
    networks:
      - nas_network

  videotranscoder:
    build: ./videotranscoder
    container_name: videotranscoder
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - ${LOCAL_DOWNLOADS_PATH:-shared_downloads}:/share
    networks:
      - nas_network

  nas:
    image: dperson/samba
    container_name: nas
    restart: unless-stopped
    environment:
      - TZ=UTC
      - WORKGROUP=WORKGROUP
      # Format: user;password[;ID;group]
      - USERID=1000
      - USER=FreakiestNas;FreakiestNas
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - shared_downloads:/share
    command: '-s "Downloads;/share;yes;no;yes;all;none;none" -u "FreakiestNas;FreakiestNas" -p'
    networks:
      - nas_network
    profiles:
      - with_nas

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - nas_network

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "3002:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
    networks:
      - nas_network

volumes:
  shared_downloads:
    driver: local
    driver_opts:
      type: none
      device: /share/docker_volumes/shared_downloads
      o: bind
  ollama_data:
    driver: local
    driver_opts:
      type: none
      device: /share/docker_volumes/ollama_data
      o: bind
  grafana_data:
  influxdb_data:

networks:
  nas_network:
    driver: bridge
