services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - shared_downloads:/downloads
    networks:
      - nas_network

  videotranscoder:
    build: ./videotranscoder
    container_name: videotranscoder
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - shared_downloads:/share
    networks:
      - nas_network

  nas:
    image: dperson/samba
    container_name: nas
    restart: unless-stopped
    environment:
      - TZ=UTC
      - WORKGROUP=WORKGROUP
      # Format: user;password[;ID;group]
      - USERID=1000
      - USER=FreakiestNas;FreakiestNas
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - shared_downloads:/share
    command: '-s "Downloads;/share;yes;no;yes;all;none;none" -u "FreakiestNas;FreakiestNas" -p'
    networks:
      - nas_network

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - nas_network

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
    depends_on:
      - ollama
    networks:
      - nas_network

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=homelab
      - DOCKER_INFLUXDB_INIT_BUCKET=docker_metrics
    networks:
      - nas_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
    networks:
      - nas_network

volumes:
  shared_downloads:
  ollama_data:
  grafana_data:
  influxdb_data:

networks:
  nas_network:
    driver: bridge
